version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: novus
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000