"""
Migrations are Django’s way of propagating changes you make to your models 
(adding a field, deleting a model, etc.) into your database schema.
They’re designed to be mostly automatic but if you need more details you can read more
at https://docs.djangoproject.com/en/3.2/topics/migrations/
"""
# Generated by Django 3.2.5 on 2021-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.PositiveIntegerField(default=0)),
                ('max_per_user', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
