# Generated by Django 3.2 on 2021-04-28 21:17
import random

from django.db import migrations


def create_fake_data(apps, schema_editor):
    create_user(apps)
    clients = create_clients(apps)
    accounts = create_accounts(apps, clients)
    create_transactions(apps, accounts)


def create_user(apps):
    User = apps.get_model('auth', 'User')
    User.objects.create_user('bob', 'bob@marley.com', 'marley')


def create_clients(apps):
    Client = apps.get_model('backoffice', 'Client')
    return Client.objects.bulk_create([
            Client(name="Annie"),
            Client(name="Zorg"),
         ])


def create_accounts(apps, clients):
    Account = apps.get_model('backoffice', 'Account')
    return Account.objects.bulk_create([Account(client=client, balance=random.randint(0, 100)) for client in clients])


def create_transactions(apps, accounts):
    Transaction = apps.get_model('backoffice', 'Transaction')
    for account in accounts:
        Transaction.objects.create(
            account=account,
            amount=random.randint(1, 10000),
            currency=random.choice(['EUR', 'GBP', 'USD']),
            direction=random.choice(['IN', 'OUT']),
            counterparty_name=random.choice(['Mikki', 'Valentine', 'Andrea']),
            counterparty_account=random.randint(1000000, 9999999),
            counterparty_sort_code=random.randint(100000, 999999),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_fake_data),
    ]
